# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - api-fitapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'api/swagger.json'
        env:
          host: "api-fitapp.azurewebsites.net"
      
      - name: Replace multiple strings in files
        uses: flcdrg/replace-multiple-action@v1.0.143
        with:
          # Globbing pattern to match files to search
          files: 'api/configuracoes.js'
          # JSON array of strings to find and replacements
          find: '[{ "find": "localhost", "replace": "db-fitapp.mysql.database.azure.com" }, { "find": "fitapp_user", "replace": "db_fitapp_admin" },  { "find": "4542", "replace": "zK8a8bDU7C5D" }]'
      
      - name: npm install, build, and test
        run: |
          cd api
          npm install
          npm run build --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'api-fitapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7616C427BEA247C7A36373B9F8705F02 }}
          package: .
